[package]
name = "mdbook-graphviz"
version = "0.1.0"
authors = ["Dylan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.3"
clap = "2.33"
serde_json = "1.0"
pulldown-cmark = "0.5"
pulldown-cmark-to-cmark = "1.2.3"